
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: ["14.0"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  container-jobs:
    runs-on: self-hosted
    environment: Test
    container: 
      image: monemaweb/odoo-test:14.0
      options: --user root
      env:
        HOST: db
        USER: odoo
        PASSWORD: odoo

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: odoo
          POSTGRES_USER: odoo
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: echo "Database password is $PASSWORD $DINAR_TOKEN $BOT_TOKEN ${{ env.PASSWORD }} ${{ env.DINAR_TOKEN }} ${{ env.BOT_TOKEN }}"
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Switch to Current Branch
        run: git checkout ${{ env.BRANCH }}
      - name: Run initdb
        run: |
          set && odoo -i contract_sequence -d db_test --stop-after-init --no-http --db_host $HOST  --db_user $USER --db_password $PASSWORD
      - name: Run unit tests
        run: |
          pytest -p no:warnings -rA -s --odoo-database=db_test --junitxml=coverage/local/junit.xml --cov-report html:coverage/local/cov.html --cov-report xml:coverage/local/coverage.xml --cov-report annotate:coverage/local/cov_annotate --cov=/__w/contract_sequence/contract_sequence /__w/contract_sequence/contract_sequence

  