
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: ["14.0"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  container-jobs:
    runs-on: self-hosted
    container: 
      image: monemaweb/odoo-test:14.0
      options: --user root
      env:
        ADDONS_PATH: /__w/contract,/__w/monema
        HOST: postgres
        USER: odoo
        PASSWORD: odoo

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: odoo
          POSTGRES_USER: odoo
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout OCA/contract
        uses: actions/checkout@v2
        with:
          repository: OCA/contract
          ref: ${{ env.BRANCH }}
          path: contract
          fetch-depth: 0
      - name: Checkout Contract Sequence
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH }}
          path: monema/contract_sequence
          fetch-depth: 0
      - name: Run initdb
        run: |
          odoo -i contract_sequence -d db_test --stop-after-init --no-http --db_host $HOST  --db_user $USER --db_password $PASSWORD
      - name: Run unit tests
        run: |
          pytest -p no:warnings -rA -s --odoo-database=db_test --junitxml=/__w/contract_sequence/contract_sequence/junit.xml --cov-report html:/__w/contract_sequence/contract_sequence/cov.html --cov-report xml:/__w/contract_sequence/contract_sequence/coverage.xml --cov-report annotate:/__w/contract_sequence/contract_sequence/cov_annotate --cov=/__w/contract_sequence/contract_sequence/monema/contract_sequence/ /__w/contract_sequence/contract_sequence/monema/contract_sequence/

  